Allow label elements
jwohlfert23/react-native-tag-input pull request #63
Opened 2018-05-25 03:18 UTC by nol13

Allow labelExtractor to return an element instead of a string, to allow for showing custom icons or conditional styling and such.

2018-05-26 19:11 UTC, Ashoat requested changes
Thanks for this PR, @nol13. I think you got the types right! Did you try running `flow` to make sure everything typechecks?

I have some requested changes inline. Other than that, for my curiosity's sake - what do you need this new prop for?

2018-05-26 19:11 UTC, Ashoat commented on README.md
> +| labelExtractor       | (Required) Function to extract string value for label from item. May also return an element to be shown in place of text.
Can you update this to say:

> "May also return an element to be shown in place of text, in which case the `tagTextColor` and `tagTextStyle` props will be ignored."

2018-05-26 19:11 UTC, Ashoat commented on index.js
> +        {React.isValidElement(this.props.label) ? this.props.label :
I find that using ternary syntax inline in JSX feels pretty messy. Can you extract this condition to the start of the `render` function?

2018-05-27 08:04 UTC, nol13 commented
I did run flow. AM using it as a way to do conditional styling at the moment. We want some invalid tags to still get made into tags, but have their text show up red, while valid tags would still be gray.

Actually in real app am currently returning Text component from labelExtractor anyway, and ignoring the PropType warnings, but figured this makes it a little more flexible.

2018-05-27 15:25 UTC, merged

2018-05-27 15:28 UTC, Ashoat commented
Published in `react-native-tag-input@0.0.21`. Thanks again!