Update lifecycle functions
jwohlfert23/react-native-tag-input pull request #79
Opened 2019-12-30 10:56 UTC by dthuering

ported changes from https://github.com/Ashoat/squadcal/blob/master/native/components/tag-input.react.js for updating React lifecycle methods.

2019-12-30 11:09 UTC, dthuering commented
Hope, I ported all the changes.

2020-01-02 05:26 UTC, Ashoat requested changes
There's a lot of stuff here that seems unrelated to the React lifecycle method deprecation issue. The spacing changes and the new prop were ported from my fork, but aren't necessary to address the issue. I'm open to taking the new prop, but it would be best to keep it to a separate PR.

Outside of that, I looked back at the [changes](https://github.com/Ashoat/squadcal/commit/507c63dad8f30162ab1804b3a58171a1e3c09f93#diff-3ea50173114fbfdbcbeb8962820c8be5) I made in my project and it looks like I redesigned the data flow. It looks like you took a similar approach here, but I don't currently have a full grasp of the changes, so it would helpful if you could explain the new philosophy and how it maps to the old.

Sorry I'm making it so complicated! It may be easier to simplify this PR and just fix the component lifecycle deprecation issue without redesigning the data flow.

2020-01-02 05:26 UTC, Ashoat commented on index.js
> +"always" | "never" | "handled" | false | true;
Can you undo this spacing change?

2020-01-02 05:26 UTC, Ashoat commented on index.js
> +   */
Undo spacing

2020-01-02 05:26 UTC, Ashoat commented on index.js
> +    minHeight: PropTypes.number,
You're introducing a new prop here, but you haven't documented it in the `README`, and there's no corresponding Flow update for it. I think it's best to keep this new prop to a separate PR and limit this PR to just the fixes for the React lifecycle deprecation issue

2020-01-02 05:26 UTC, Ashoat commented on index.js
> +                  styles.textInputContainer,
Undo spacing change

2020-03-16 15:32 UTC, closed without merging